from decouple import config

JWT_SECRET = config("JWT_SECRET")
MAIL_USERNAME =config('MAIL_USERNAME')
MAIL_PASSWORD =config('MAIL_PASSWORD')
MAIL_FROM =config('MAIL_FROM')
MAIL_PORT = int(config('MAIL_PORT'))
MAIL_SERVER =config('MAIL_SERVER')
MAIL_FROM_NAME =config('MAIN_FROM_NAME')
TEMPLATE_FOLDER = config('TEMPLATE_FOLDER')
EMAIL_VERIFICATION_BASE_URL = config('EMAIL_VERIFICATION_BASE_URL')
PASSWORD_RESET_BASE_URL = config('PASSWORD_RESET_BASE_URL')
EMAIL_VERIFICATION_TEMPLATE = config('EMAIL_VERIFICATION_TEMPLATE')
PASSWORD_RESET_TEMPLATE = config('PASSWORD_RESET_TEMPLATE')